---
- name: Add PostgreSQL apt repository signing key
  apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc
  sudo: yes

- name: Add PostgreSQL apt repository
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ {{ ansible_distribution_release }}-pgdg main
    update_cache: yes
  sudo: yes

- name: Install PostgreSQL packages
  apt:
    name:
      - postgresql-10
      - libpq-dev
  sudo: yes

- name: Install Ansible PostgreSQL dependencies
  pip:
    name: psycopg2
  sudo: yes

- name: Start PostgreSQL service
  service:
    name: postgresql
    state: started
  sudo: yes

- name: Get local username
  command: whoami
  register: local_username

- name: Set up default PostgreSQL user
  postgresql_user:
    name: "{{ local_username.stdout }}"
    role_attr_flags: SUPERUSER
  sudo: yes
  sudo_user: postgres

- name: Set up default PostgreSQL database
  postgresql_db:
    name: "{{ local_username.stdout }}"
  sudo: yes
  sudo_user: postgres

- name: Stop PostgreSQL service
  service:
    name: postgresql
    state: stopped
  sudo: yes
