---
- name: Add Crowdin apt repository signing key
  apt_key: url=https://artifacts.crowdin.com/repo/GPG-KEY-crowdin
  become: yes

- name: Add Crowdin apt repository
  apt_repository:
    repo: deb https://artifacts.crowdin.com/repo/deb/ /
    update_cache: yes
  become: yes

- name: Install Crowdin CLI package
  apt: "name={{ item }}"
  with_items:
    - default-jre
    - crowdin
  become: yes
